#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          20
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#0F689B"
bspc config normal_border_color  "#112B40"



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=of

setxkbmap gb
feh --bg-scale ~/Downloads/ice.jpg
~/.config/polybar/launch.sh &
sleep .6
~/Downloads/igPY.bin &
sleep .5
mpd
